# Generated by Django 4.1.2 on 2022-10-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beakShape', models.CharField(max_length=180)),
                ('eyeColor', models.CharField(max_length=180)),
                ('wingsColor', models.CharField(max_length=180)),
                ('Location', models.CharField(max_length=180)),
                ('birdColor', models.CharField(max_length=180)),
            ],
        ),
    ]
